### ISSUE TITLE
【依頼】フリマアプリ挙動確認	

### ISSUE THREAD

**Issue by mzw86020424** [mzw86020424/furima-32049#9]
- 自身のフリマアプリのURL
https://furima-32049.herokuapp.com/
- Basic認証のIDとパスワード
ID:admin
PASS:2222
- 出品者用のメールアドレスとパスワード
アドレス:taro@test
PASS:taro123
- 購入者用のメールアドレスとパスワード
アドレス:jiro@test
PASS:jiro123
- 購入用カードの番号・期限・セキュリティコード
番号:4242424242424242
期限:3/23
CVC:123

**Comment by keisukekodama** [comment]
![最終課題終了_おめでとう画像](https://user-images.githubusercontent.com/44963290/100499353-377ce500-31ac-11eb-87cc-2f4bfe1d4012.png)
おめでとうございます！LGTMです！🎉

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします**。
